import Groq from "groq-sdk";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { pickProbability } from "@/lib/picks";
import type { Prediction } from "@/lib/api";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

const SYSTEM = `You are BetIQ's AI betting assistant. Help users build football accumulators from AI-predicted matches. The user books them on SportyBet from their bet slip.

Each prediction has: home, away, date, tip_code ("1"=home win, "X"=draw, "2"=away win, "1X"/"X2"/"12"=double chance, "?"/"Skip"=no tip), tip_1x2, goals_type ("Banker"/"Asian"/"Skip"), conf (the model's probability that tip_code wins), league, flag.

RULES:
1. ONLY pick games where tip_code is exactly "1", "X", or "2". Never pick "1X", "X2", "12", "?", or "Skip" — these cannot be booked on SportyBet. If a game's tip_code is not "1", "X", or "2", skip it entirely.
2. Prefer Banker games. Never pick more than 10 games.
3. When you present picks, ALWAYS include this block at the end of your reply:

<selections>
[{"home":"TeamA","away":"TeamB","date":"YYYY-MM-DD","tip_code":"1","tip_1x2":"Home Win","goals_confidence":0.82,"league":"PL","flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿"}]
</selections>

4. Be friendly and concise. Use football emojis occasionally.
5. After showing picks, say: "Tap **Add to slip & book on SportyBet** to get your booking code."
6. If asked to swap or remove a game, update the selections block.
7. NEVER invent, guess, or generate a booking code yourself. You do not have access to SportyBet. The booking code is generated by the bet slip when the user books it. If you produce any string that looks like a code, it will be wrong and mislead the user.`;

const API_BACKEND = process.env.NEXT_PUBLIC_API_URL || "https://betiq-backend-jcwa.onrender.com";

// The assistant costs money per message: signed-in premium users only (or
// everyone signed in while the paywall is off), within these limits.
const MAX_MESSAGES = 30;
const MAX_USER_CHARS = 2000;
const MAX_ASSISTANT_CHARS = 12000;  // replies carry a <selections> block
const MAX_PREDICTIONS = 100;
const PER_MINUTE = 8;
const recent = new Map<string, number[]>();  // per server instance

function rateLimited(userId: string): boolean {
  const now = Date.now();
  const hits = (recent.get(userId) ?? []).filter(t => now - t < 60_000);
  if (hits.length >= PER_MINUTE) return true;
  hits.push(now);
  recent.set(userId, hits);
  if (recent.size > 5000) recent.clear();
  return false;
}

async function paywallOn(): Promise<boolean> {
  try {
    const r = await fetch(`${API_BACKEND}/api/config/paywall`, { next: { revalidate: 60 } });
    return (await r.json())?.enabled !== false;
  } catch {
    return true;
  }
}

function hasPremium(meta: Record<string, unknown> | undefined): boolean {
  return meta?.subscription === "premium" && new Date(String(meta?.subscription_expires ?? 0)) > new Date();
}

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "not_authenticated" }, { status: 401 });
    if (await paywallOn()) {
      const user = await (await clerkClient()).users.getUser(userId);
      if (!hasPremium(user.publicMetadata as Record<string, unknown>))
        return NextResponse.json({ error: "premium_required" }, { status: 402 });
    }
    if (rateLimited(userId)) return NextResponse.json({ error: "slow_down" }, { status: 429 });

    const body = await req.json();
    const messages = Array.isArray(body?.messages) ? body.messages : [];
    const predictions = Array.isArray(body?.predictions) ? body.predictions : [];
    if (!messages.length || messages.length > MAX_MESSAGES ||
        messages.some((m: { role?: unknown; content?: unknown }) =>
          (m?.role !== "user" && m?.role !== "assistant") ||
          typeof m?.content !== "string" ||
          m.content.length > (m.role === "user" ? MAX_USER_CHARS : MAX_ASSISTANT_CHARS)))
      return NextResponse.json({ error: "invalid_messages" }, { status: 400 });

    // Slim predictions to only bookable tips and essential fields
    const slim = (predictions as Record<string, unknown>[])
      .slice(0, MAX_PREDICTIONS)
      .filter((p) => p.tip_code && !["?", "Skip"].includes(p.tip_code as string))
      .map((p) => ({
        home: p.home,
        away: p.away,
        date: p.date,
        tip_code: p.tip_code,
        tip_1x2: p.tip_1x2,
        goals_type: p.goals_type,
        // Probability of the tip itself — not goals_confidence, which is the goals tip's
        conf: (() => {
          const prob = pickProbability(p as unknown as Prediction);
          return prob === null ? "—" : Math.round(prob * 100) + "%";
        })(),
        league: p.league,
        flag: p.flag,
      }));

    // Build message list: system → context injection → conversation history
    const groqMessages: Groq.Chat.ChatCompletionMessageParam[] = [
      { role: "system", content: SYSTEM },
      {
        role: "user",
        content: `Here are today's available predictions:\n${JSON.stringify(slim)}`,
      },
      {
        role: "assistant",
        content: "Got it — predictions loaded. What kind of accumulator would you like?",
      },
      // Real conversation (skip any leading assistant greeting)
      ...(() => {
        const firstUserIdx = messages.findIndex((m: { role: string }) => m.role === "user");
        return firstUserIdx === -1 ? [] : messages.slice(firstUserIdx);
      })().map((m: { role: string; content: string }) => ({
        role: m.role as "user" | "assistant",
        content: m.content,
      })),
    ];

    // Last user message (used for logging + Groq call)
    const lastMessage = messages[messages.length - 1];

    // Log query for admin analytics (fire-and-forget)
    fetch(`${API_BACKEND}/api/log/query`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query: (lastMessage?.content ?? "").slice(0, 200) }),
    }).catch(() => {});

    // Groq retired llama-3.3-70b-versatile on 2026-08-16; gpt-oss-120b is its
    // documented replacement. It reasons before replying and those tokens count
    // toward the cap, hence low effort and headroom above the ~1500 we need.
    const completion = await groq.chat.completions.create({
      model: "openai/gpt-oss-120b",
      messages: groqMessages,
      max_completion_tokens: 2500,
      reasoning_effort: "low",
      temperature: 0.4,
    });

    const text = completion.choices[0]?.message?.content ?? "";
    return NextResponse.json({ message: text });

  } catch (err: unknown) {
    console.error("[chat/groq]", err);
    return NextResponse.json({ error: "assistant_unavailable" }, { status: 500 });
  }
}
